### ISSUE TITLE
fetch all dependencies (sass etc.) via npm + composer (currently ruby gem dependencies)

### ISSUE THREAD

**Issue by kuttnerd** [croox/generator-wp-dev-env#3]
+ update readme idiot friendly (add "npm install" etc.)

**Comment by jhotadhari** [comment]
## Sass and Ruby

Currently `grunt-contrib-sass` is used to compile sass: "This task requires you to have Ruby and Sass installed"
We could use `grunt-sass`: Compile Sass to CSS using Dart Sass or Node Sass.

Thoughts about migrating to `node-sass` (wrapper for `LibSass`).
- pro: [compatibility](http://sass-compatibility.github.io/) looks good.
- pro: Compiling is up to [4000% faster](https://www.moovweb.com/libsass/)!
- con: No `compass` anymore and apparently will never be compatible.
If only the mixins are required, one could use [`compass-importer`](https://github.com/haithembelhaj/compass-importer) as workaround.
Could either bundle the `compass-importer` into `wp-dev-env-grunt`, or needs to be added manually per project (hooked in `my-project-root/grunt/hooks/`).

## convert from ImageMagick

ImageMagick is used only for the single purpose to create the screenshot.
If ImageMagick is not installed, the screenshot creation will be just skipped.
To use something "pure" node instead would require many dependencies and the project would be a way more bulky.
Just for generating a single screenshot? I'm ok with the current state.

## xgettext

I think its ok having that dependency. what do you think?
**Alternatives would be nice**, since xgettext often fails (my experience) and the grunt task wrapper doesn't log the error or anything (it just looks all good, but isn't).

## grunt-contrib-compress

I remember, you cloned a project and tried to `npm install` on your mac.
There was some error with `grunt-contrib-compress` and it couldn't be installed.
**Do you wanna try again?** may be we try together?

**Comment by jhotadhari** [comment]
Just generated new theme based on `underboots` to test with `grunt-sass`

`sass` task completed in 5200ms using `grunt-contrib-sass`.
`sass` task completed in 650ms after migrating to `grunt-sass`.

Released `wp-dev-env-grunt#0.7.0`, migrated to `grunt-sass`.
See https://github.com/croox/wp-dev-env-grunt/commit/557e5a3ff52ac48df407c37fff34d7dc17deb6a2

**Still need to update the generator.**

**Comment by kuttnerd** [comment]
wow the speed improvement is great :-D
for me mixins are not directly necessary, but they're useful for sure ...

**Comment by jhotadhari** [comment]
Released `generator-wp-dev-env#0.8.0`
https://github.com/croox/generator-wp-dev-env/releases/tag/0.8.0

**Comment by jhotadhari** [comment]
ich versuche mal die xgettext dependency los zu werden
vielleicht klappt das https://www.npmjs.com/package/wp-pot

aaaaakku leer

**Comment by kuttnerd** [comment]
wieso xgettext loswerden? wg zeitersparnis?

**Comment by jhotadhari** [comment]
ich dachte das wäre die issue?

**Comment by jhotadhari** [comment]
also hier eingebaut im wde-grunt 0.9.0 https://github.com/croox/wp-dev-env-grunt/commit/2b1c395936a8a21d8552196ba4e61e737cd84761

und wird jetzt auch im generator verwendet https://github.com/croox/generator-wp-dev-env/commit/79d7b10aba0b8ccda1de5331c5bac67e3e78baee
und auch `gettext` auch überall aus den docs geschmissen 

arepo benutzt schon die neue wde-grunt 0.9.0



und `convert from ImageMagick` bleibt von mir aus drin.
sollte nur so umgebaut werden, dass das ding nicht abstürzt. also als optionale dep
